- hosts: localhost
  gather_facts: no

  # Assigning the variable values
  vars:
    network_values:
     - internet
     - l2
     - l3
     - other
    network_file_values:
     - internet.xml
     - l2.xml
     - l3.xml
     - other.xml
    bridge_values:
     - sw1
     - sw2
     - sw3
     - sw4

  ## Existing code to verify Package installations    
  tasks:
   - name: Check for qemu-kvm
     apt:
       name: qemu-kvm
       state: present

   - name: Check for libvirt packages and ovs
     apt:
      name: "{{ item }}"
      state: present
     with_items:
       - libvirt-bin
       - virt-manager
       - virt-viewer
       - virtinst
       - openvswitch-switch

   - name: Defining  network
     virt_net:
      command: define
      name: "{{item.0}}"
      xml: '{{ lookup("template", "{{item.1}}") }}'
     with_together:
       - "{{network_values}}"
       - "{{network_file_values}}"

   - name: Start the network
     virt_net:
      command: create
      name: "{{item}}"
     with_items:
       - "{{network_values}}"

   - name: Create an OvS bridge
     openvswitch_bridge:
      bridge: "{{item}}"
      state: present
     with_items:
       - "{{bridge_values}}"


